import type { Metadata } from "next";

import "./_UI/styles/global.css";
import { fontInter } from "./_UI/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontInter.className}`}>{children}</body>
    </html>
  );
}
